[package]
name = "serum-engine"
version = "0.1.0"
edition = "2021"
"license" = "MPL-2.0"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
embed-resource = "1.7"